## spring
management:
  endpoints:
    web: ## actuator 기능을 web 에 모두 노출하겠다는 것
      exposure:
        include: "*"


## logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${LOG_LEVEL_PATTERN:%-5p} ${PID} --- [%15.15t] %-40.40logger{39} :%06L : %m%n"
  level:
    root: info
    web: debug
    hello: debug